### ISSUE TITLE
java.lang.NoClassDefFoundError when using the antisamy-1.4.1.xml policy file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [andresriancho/owaspantisamy#95]
```
What steps will reproduce the problem?
1. set the policy file to antisamy-1.4.1.xml
2. try to clean the following code:
<div style="background:url('javascript:alert('xss 2')')">Some bad HTML!</div>
3. You get an error: java.lang.NoClassDefFoundError: 
org/apache/commons/httpclient/HttpContentTooLargeException

What is the expected output? What do you see instead?

Cleaned HTML

What version of the product are you using? On what operating system?

1.4.1 on Windows server 2003 or Windows Vista

Please provide any additional information below.

This works fine with the antisamy-slashdot-1.4.1.xml, but this prolicy file is 
way more restrictive and removes a lot of the user code like a simple img tag.


```

Original issue reported on code.google.com by `huba...@gmail.com` on 22 Nov 2010 at 10:11
